export const productos = [{id:1,nombre:"abanico",foto_1:"/productos/foto_1.jpeg",foto_2:"/productos/foto_12.jpeg",foto_3:"/productos/foto_2.jpeg",minimo:"50",},
{id:3,nombre:"bolsa",foto_1:"/productos/foto_80.jpg",minimo:"20",},
{id:4,nombre:"bolsa regalo",foto_1:"/productos/foto_32.jpeg",foto_2:"/productos/foto_305.jpg",minimo:"20",},
{id:5,nombre:"botella",foto_3:"/productos/foto_77.jpg",minimo:"20",},
{id:6,nombre:"botella termo",foto_1:"/productos/foto_55.jpeg",minimo:"20",},
{id:8,nombre:"buzo",foto_1:"/productos/foto_5.jpeg",foto_2:"/productos/foto_213.jpg", minimo:"20",},
{id:9,nombre:"campera",foto_1:"/productos/foto_64.jpeg", minimo:"20",},
{id:10,nombre:"bandana",foto_1:"/productos/foto_292.jpg",foto_2:"/productos/foto_104.jpeg", minimo:"20",},
{id:11,nombre:"conjunto",foto_1:"/productos/foto_4.jpeg",foto_2:"/productos/foto_27.jpeg",foto_3:"/productos/foto_8.jpeg",minimo:"20",},
{id:12,nombre:"conservadora",foto_1:"/productos/foto_25.jpeg",foto_2:"/productos/foto_41.jpeg",foto_3:"/productos/foto_39.jpeg",minimo:"20",},
{id:13,nombre:"gorra",foto_1:"/productos/foto_3.jpeg",foto_2:"/productos/foto_13.png",foto_3:"/productos/foto_6.jpeg",minimo:"20",},
{id:14,nombre:"gorra + remera",foto_1:"/productos/foto_69.jpeg",foto_2:"/productos/foto_76.png", minimo:"20",},
{id:15,nombre:"gorra + remera + buzo",foto_1:"/productos/foto_63.jpeg", minimo:"20",},
{id:16,nombre:"jardinero",foto_1:"/productos/foto_23.jpeg", minimo:"20",},
{id:17,nombre:"lapicera",foto_1:"/productos/foto_288.jpg",foto_2:"/productos/foto_50.jpeg", minimo:"20",},
{id:2,nombre:"llavero 3D/goma",foto_1:"/productos/foto_14.jpeg", minimo:"20",},
{id:18,nombre:"llavero acrilico",foto_1:"/productos/foto_11.jpeg",foto_2:"/productos/foto_24.jpeg", minimo:"20",},
{id:19,nombre:"llavero correa",foto_1:"/productos/foto_65.jpeg", minimo:"20",},
{id:20,nombre:"lona",foto_1:"/productos/foto_68.jpeg",foto_2:"/productos/foto_101.jpg",foto_3:"/productos/foto_81.jpg",minimo:"20",},
{id:21,nombre:"parasol",foto_1:"/productos/foto_28.jpeg",foto_2:"/productos/foto_109.jpg",foto_3:"/productos/foto_79.jpg",minimo:"20",},
{id:22,nombre:"pelota paleta",foto_1:"/productos/foto_22.jpeg", minimo:"20",},
{id:23,nombre:"pelotita",foto_1:"/productos/foto_17.jpeg",foto_2:"/productos/foto_110.jpg",foto_3:"/productos/foto_18.jpeg",minimo:"20",},
{id:24,nombre:"piluso",foto_1:"/productos/foto_35.jpeg",foto_2:"/productos/foto_40.jpeg",foto_3:"/productos/foto_43.jpeg",minimo:"20",},
{id:25,nombre:"piluso + remera",foto_1:"/productos/foto_44.jpeg", minimo:"20",},
{id:26,nombre:"pin",foto_1:"/productos/foto_281.jpg", minimo:"20",},
{id:27,nombre:"porta bebida",foto_1:"/productos/foto_16.jpeg", minimo:"20",},
{id:29,nombre:"remera",foto_1:"/productos/foto_21.jpeg",foto_2:"/productos/foto_37.jpeg",foto_3:"/productos/foto_66.jpeg",minimo:"20",},
{id:30,nombre:"riñonera",foto_1:"/productos/foto_62.jpeg",foto_2:"/productos/foto_263.jpg",minimo:"20",},
{id:32,nombre:"vaso",foto_1:"/productos/foto_73.jpg",foto_2:"/productos/foto_258.jpg", minimo:"20",},
{id:33,nombre:"vaso termico",foto_1:"/productos/foto_214.jpg",foto_2:"/productos/foto_216.jpg", minimo:"20",},];